[package]
name = "meshopt-rs"
version = "0.1.0"
authors = ["yzsolt"]
edition = "2021"

[features]
# Experimental APIs have unstable interface and might have implementation that's not fully tested or optimized
experimental = []

[dev-dependencies]
miniz_oxide = "0.4"
tobj = "2.0"
